name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
         pwd
         ls -la
         echo Hello, world!
         docker build .
         pwd
         pip install -r requirements.txt 
         mkdir folder && pwd
         sh who_answers.sh 

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  jira_script:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
         pwd
         ls -la
         echo Hello, world!
         docker build .
         pwd
         pip install -r requirements.txt 
         mkdir folder && pwd
         sh who_answers.sh
         find . -name '*.pyc' -delete
         python -m jira_helper

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.          
