name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: |
         echo Hello, world!
         mkdir folder && cd folder && pwd

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  jira_script:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
         echo Hello, world!
         pip install jira
         python -m jira_helper
         mkdir folder && cd folder1

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.          
